[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.123.0"  # Use your Hugo version here

[context.production.environment]
  HUGO_ENV = "production"
